# Generated by Django 5.2.7 on 2025-10-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlabLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slab_level', models.CharField(max_length=50, unique=True)),
                ('upper_range', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_user', models.TextField()),
            ],
        ),
    ]
